"https://{default}/":
    type: upstream
    upstream: "varnish:http"
    cache:
        # This cache does not support Tagging, purging, and user context hash, we can't use this for HttpCache.
        # Instead use one of:
        # - Varnish (default)
        # - Fastly (needed on Enterprise Dedicated)
        # - Symfony Proxy (AppCache, only for single server, limited performance and ESI support)
        enabled: false

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
